# Generated by Django 5.0.4 on 2024-04-30 07:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_login_j',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='branch_code',
            field=models.CharField(max_length=4, verbose_name='کد شعبه'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='national_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='کدملی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='organization_code',
            field=models.IntegerField(default=0, verbose_name='کد سازمان'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='organization_name',
            field=models.CharField(max_length=32, verbose_name='نام سازمان'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='personnel_code',
            field=models.IntegerField(default=0, verbose_name='کدپرسنلی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='post_code',
            field=models.IntegerField(default=0, verbose_name='کد پست'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='post_level_code',
            field=models.IntegerField(default=0, verbose_name='کد سطح پست'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='post_level_name',
            field=models.CharField(max_length=32, verbose_name='نام سطح پست'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='post_name',
            field=models.CharField(max_length=32, verbose_name='نام پست'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status_name',
            field=models.CharField(max_length=16, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_organization_name',
            field=models.CharField(max_length=32, verbose_name='نام زیر سازمان'),
        ),
    ]
