# Generated by Django 5.0.4 on 2024-04-30 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_last_login_j_alter_customuser_branch_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_login_j',
        ),
    ]
